"""Final2  Migration

Revision ID: 09093d4f2d0a
Revises: db83a825b2ca
Create Date: 2022-05-19 11:01:22.155550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09093d4f2d0a'
down_revision = 'db83a825b2ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('title', sa.String(length=255), nullable=True))
    op.drop_column('blogs', 'topic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('topic', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('blogs', 'title')
    # ### end Alembic commands ###
